# Generated by Django 3.1.7 on 2021-12-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211220_1339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='UserInfo',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='person',
            new_name='user_info',
        ),
    ]
