# Generated by Django 3.1.7 on 2021-12-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211220_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_info',
        ),
        migrations.AddField(
            model_name='customuser',
            name='attvalid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='bdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='document',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='findate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gdzs',
            field=models.TextField(blank=True, db_column='GDZS', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='getdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='passdate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='post',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rtp',
            field=models.IntegerField(blank=True, db_column='RTP', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='why',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
