# Generated by Django 3.1.7 on 2021-12-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211220_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='findate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='getdate',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='attvalid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Аттестация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bdate',
            field=models.TextField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.TextField(blank=True, null=True, verbose_name='Удостоверение'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gdzs',
            field=models.TextField(blank=True, db_column='GDZS', null=True, verbose_name='ГДЗС'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passdate',
            field=models.TextField(blank=True, null=True, verbose_name='Дата сдачи на пропуск'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rtp',
            field=models.BooleanField(blank=True, db_column='RTP', null=True, verbose_name='РТП'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='why',
            field=models.TextField(blank=True, null=True, verbose_name='Почему не подлежит аттестации'),
        ),
    ]
