# Generated by Django 3.1.7 on 2022-01-02 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20211220_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tables',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='attvalid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.passedapprovals', verbose_name='Аттестация'),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='approvalsname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.attvalid'),
        ),
    ]
