# Generated by Django 3.1.7 on 2022-01-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220102_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attvalid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
