# Generated by Django 3.1.7 on 2022-01-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_customuser_attvalid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='Должность'),
        ),
    ]
