# Generated by Django 3.1.7 on 2022-01-02 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220102_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
