# Generated by Django 3.1.7 on 2022-01-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220102_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='value',
            field=models.TextField(blank=True, null=True, unique=True),
        ),
    ]
