# Generated by Django 3.1.7 on 2022-01-02 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220102_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedapprovals',
            name='peopleid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser'),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='result',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
