# Generated by Django 3.1.7 on 2022-01-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220102_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passedapprovals',
            options={'verbose_name': 'Аттестация', 'verbose_name_plural': 'Аттестации'},
        ),
        migrations.AlterModelTable(
            name='passedapprovals',
            table=None,
        ),
    ]
