# Generated by Django 3.1.7 on 2022-01-02 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220102_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='attvalid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.passedapprovals', verbose_name='Аттестация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post', verbose_name='Должность'),
        ),
    ]
