# Generated by Django 3.1.7 on 2022-01-02 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220102_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoAttestation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='Причина')),
            ],
            options={
                'verbose_name': 'Причина неаттестации',
                'verbose_name_plural': 'Причины неаттестации',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='why',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.noattestation', verbose_name='Почему не подлежит аттестации'),
        ),
    ]
