# Generated by Django 3.1.7 on 2022-01-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20220102_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passedapprovals',
            name='why',
        ),
    ]
