# Generated by Django 3.1.7 on 2022-01-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20220102_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialTrainingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Начало первичной подготовки')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Конец первичной подготовки')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
