# Generated by Django 3.1.7 on 2022-01-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20220104_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.initialtrainingperiod', verbose_name='Период первичной подготовки'),
        ),
    ]
