# Generated by Django 3.1.7 on 2022-01-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_customuser_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initialtrainingperiod',
            options={'verbose_name': 'Период первичной подготовки', 'verbose_name_plural': 'Периоды первичной подготовки'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='attvalid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.passedapprovals', verbose_name='Аттестация'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='passdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи на пропуск'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.initialtrainingperiod', verbose_name='Период первичной подготовки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.post', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='attdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='profdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
