# Generated by Django 3.1.7 on 2022-01-09 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20220109_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passedapprovals',
            name='approvalsname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.attvalid'),
        ),
    ]
