# Generated by Django 3.1.7 on 2022-01-09 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20220109_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'Звание', 'verbose_name_plural': 'Звания'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.rank', verbose_name='Звание'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Звание'),
        ),
    ]
