# Generated by Django 3.1.7 on 2022-01-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20220109_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Звание'),
        ),
    ]
