# Generated by Django 3.1.7 on 2022-01-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20220109_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Удостоверение'),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='why',
            field=models.TextField(blank=True, null=True, verbose_name='Почему не прошел аттестацию'),
        ),
    ]
