# Generated by Django 3.1.7 on 2022-01-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20220110_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvals',
            options={'verbose_name': 'Вид аттестации', 'verbose_name_plural': 'Виды аттестации'},
        ),
        migrations.RenameField(
            model_name='approvals',
            old_name='name',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='approvalsname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.approvals', verbose_name='Название аттестации'),
        ),
        migrations.AlterModelTable(
            name='approvals',
            table=None,
        ),
        migrations.DeleteModel(
            name='Attvalid',
        ),
    ]
