# Generated by Django 3.1.7 on 2022-01-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20220110_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvals',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
