# Generated by Django 3.1.7 on 2022-01-10 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20220110_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDZS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(blank=True, null=True)),
                ('possible', models.BooleanField(blank=True, null=True)),
                ('fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
                ('why_not', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.noattestation', verbose_name='Почему не подлежит аттестации')),
            ],
            options={
                'verbose_name': 'ГДЗС',
                'verbose_name_plural': 'ГДЗС',
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gdzs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.gdzs', verbose_name='ГДЗС'),
        ),
    ]
