# Generated by Django 3.1.7 on 2022-01-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20220110_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='passdate',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rtp',
        ),
        migrations.AddField(
            model_name='post',
            name='passdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сдачи на пропуск'),
        ),
        migrations.AddField(
            model_name='post',
            name='rtp',
            field=models.BooleanField(blank=True, db_column='RTP', null=True, verbose_name='РТП'),
        ),
        migrations.AlterField(
            model_name='post',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Должность'),
        ),
    ]
