# Generated by Django 3.1.7 on 2022-01-11 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20220111_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdzs',
            name='fullname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL, verbose_name='ГДЗС'),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='why',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Почему не прошел аттестацию'),
        ),
        migrations.AlterField(
            model_name='post',
            name='value',
            field=models.CharField(max_length=30, verbose_name='Должность'),
        ),
    ]
