# Generated by Django 3.1.7 on 2022-01-11 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20220111_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fullname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='main.customuser'),
        ),
    ]
