# Generated by Django 3.1.7 on 2022-01-17 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20220111_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdzs',
            name='fullname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='gdzs',
            name='possible',
            field=models.BooleanField(blank=True, null=True, verbose_name='Подлежит аттестации ГДЗС'),
        ),
        migrations.AlterField(
            model_name='gdzs',
            name='value',
            field=models.BooleanField(blank=True, null=True, verbose_name='ГДЗC'),
        ),
        migrations.AlterField(
            model_name='initialtrainingperiod',
            name='fullname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='attdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата аттестации'),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='profdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата профосмотра'),
        ),
        migrations.AlterField(
            model_name='passedapprovals',
            name='result',
            field=models.BooleanField(blank=True, null=True, verbose_name='Аттестован'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fullname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='post',
            name='rtp',
            field=models.BooleanField(blank=True, null=True, verbose_name='РТП'),
        ),
    ]
